#!/bin/sh

export SITE=${1:-1}
echo ++++ acq480_init_two_lane $SITE
set.sys /dev/acq400.${SITE}.knobs/acq480_two_lane_mode 1
/usr/local/bin/acq480_knobs acq480_setTwoWireMode
/usr/local/CARE/acq480_map16 $SITE


