#!/bin/sh
# configure ACQ480 with internal clock.

list_int_configs() {
	speeds=""
	for file in /etc/si5326.d/si5326_33M333*
	do
		bn=$(basename $file)
		fn1=${bn%*.txt}
		speed="$speed ${fn1#si5326_33M333-*}"
	done
	echo $speeds
}

if [ "x$1" != "x" ] && [ -f $1 ]; then
	SICONF=$1
	FREQ=$(grep Frequency $1 | tail -n 1 | awk '{ print $4 }')
else
	FREQ="x"
	if [ "x$1" = "x" ]; then
		FREQ=50M
	else
		for sp in $(list_int_configs)
		do
			if [ "x$1" = "x$sp" ]; then
				FREQ=$sp
				break
			fi
		done
	fi
	if [ "$FREQ" = "x" ]; then
		echo "ERROR rate $1 not supported default to 10M"
		FREQ=10M
	fi
	SICONF=si5326_33M333-${FREQ}.txt
	FREQ=${FREQ%*M}
fi
let FREQHZ=$FREQ*1000000
		

/usr/local/epics/scripts/wait_ioc_ready
set.site 0 SIG:ZCLK_SRC INT33M
set.site 0 SYS:CLK:FPMUX ZCLK
set.site 0 SYS:CLK:DIST_CLK_SRC Si5326
set.site 0 SYS:CLK:OE_CLK1_ZYNQ 1
set.site 0 SYS:CLK:OE_CLK1_ELF1 1
load.si5326 $SICONF

train_fail=1
while [ $train_fail -ne 0 ]; do
	acq480_train
	train_fail=$?
done

/usr/local/epics/scripts/wait_ioc_ready
caput $(hostname):1:INTCLK_HZ $FREQHZ

