#!/bin/sh

for site in ${*:-1}
do
	export SITE=${site}
	/usr/local/bin/acq480_knobs acq480_map ALL 0
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT1A 1 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT1B 1 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT2A 2 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT2B 2 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT3A 3 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT3B 3 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT4A 4 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH1234_TO_OUT4B 4 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT5A 5 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT5B 5 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT6A 6 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT6B 6 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT7A 7 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT7B 7 2
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT8A 8 
	/usr/local/bin/acq480_knobs acq480_map MAP_CH5678_TO_OUT8B 8 2
done



