#!/bin/sh

VRANGE=7

get_vr() {
	echo $1 | tr \- \\n | while read xx; do
		v1=${xx%V*}
		if [ "$v1" != "$xx" ]; then
			vdec=${xx##*V}
			if [ ! -z $vdec ]; then
				v1=$((v1+1))
			fi
			echo $v1
			return
		fi
	done
}

for file in /dev/sites/[1-6]/details
do
	if [ -e $file ]; then
		source $file
		PN=${FRU_PART_NUM%% *}
		[ "x$PN" != "x" ] && VRANGE=13
		case $PN in
		ACQ480*)
			echo "# $file: FPN $FRU_PART_NUM PN $PN"		
			echo "# ACQ480 DETECTED set VRANGE LOW"
			VRANGE=7;;
		ACQ481*)
			echo "# ACQ481 DETECTED set VRANGE 6V"
			VRANGE=6;;
		ACQ424*)
			echo "# ACQ424 DETECTED set VRANGE HI"
			VRANGE=13;;
		BOLO*)
			echo "# BOLO DETECTED set VRANGE 12"
			VRANGE=12;;
		*)
			VSPEC=${PN##*-}
			VSPEC=$(get_vr $PN)
			if [ $VSPEC -gt 0 ]; then
				VRANGE=$((VSPEC+2))
				echo "# Setting VRANGE:$VRANGE detected VSPEC:$VSPEC from $PN"
			fi;;
		esac
		break
	fi
done


export VAP=$VRANGE
export VAN=-$VRANGE
echo VAP=$VAP
echo VAN=$VAN
