#!/usr/local/bin/expect

set KEY twd
if { $::argc > 0 } {
	set KEY [lindex $::argv 0]
}

proc get_ints {} {
	global KEY
	set INT2 [exec sh -c "cat /proc/interrupts | grep -i $KEY | awk '{print \$2\" \"\$3 }'"]
	return [split $INT2]
}

set old [get_ints]

while { 1 } {
	after 1000 
	set new [get_ints]
#	puts "old $old new $new"
	set d0 [expr [lindex $new 0] - [lindex $old 0]]
	set d1 [expr [lindex $new 1] - [lindex $old 1]]
	puts "$KEY CPU0 $d0 CPU1 $d1 Hz"	

	set old $new
}

