#!/bin/sh

BLOCKS=${1:-2000}

echo mgt_dram_test over $BLOCKS BLOCKS
if [ -e /mnt/local/mgt_offload_custom ]; then
	echo "WARNING: /mnt/local/mgt_offload_custom please move it out the way"
	exit 1
fi

export MGTOFFLOADCUSTOM=/usr/local/CARE/mgt_offload_custom.2x480_ramptest

echo run two sites, simulate mode, 30MSPS for full load
run0 1,2
set.site 1 simulate 1
set.site 2 simulate 1
let BP1="$BLOCKS+1"
echo mgt_run_shot $BLOCKS fill
mgt_run_shot $BP1
echo mgt_offload 0-$BLOCKS validate $MGTOFFLOADCUSTOM
let BM1="$BLOCKS-1"
mgt_offload 0-$BM1

echo mgt_dram_test complete


