#!/bin/sh

CLKMHZ=${1:-80M}

# Workaround for previously configured MBCLK_FIN setpoint
set.site 0 SIG:CLK_MB:FIN 0
set.site 0 SIG:CLK_MB:SET 0

set.site 0 SYS:CLK:FPMUX ZCLK
set.site 0 SIG:ZCLK_SRC WR31M25
load.si5326 si5326_31M25-${CLKMHZ}.txt
set.site 0 SIG:CLK_MB_READY 1

# WRTT

# This enables the synchronous divide using the WR 1 PPS
set.site 1 sync 1,0,1

# Set the WRTT source to Front Panel, Rising
set.site 0 wr_trg_src 1,0,1

