#!/bin/sh

MAX_TX=${1:-1}
ARGS=""

if [ "${MAX_TX#[0-9]*}" != "$MAX_TX" ]; then
    ARGS="--max_tx $MAX_TX"
    shift
fi
ARGS="$ARGS $@"


TX_COUNT="${1:-1}"

export WRTD_DELTA_NS=50000000
export WRTD_NICE=-10
export WRTD_VERBOSE=0
export WRTD_TICKNS=50000
WRTD_TX=1
WRTD_RX=1

[ -e /mnt/local/sysconfig/wr.sh ] && source /mnt/local/sysconfig/wr.sh

/usr/local/bin/wrtd 2>&1  $ARGS tx_immediate 


