#!/bin/sh

MAX_TX=${1:-1}
ARGS=""
SITE=${SITE:-11}
WRSH=/dev/shm/wr${SITE}.sh
eval $(sed -e 's/^/export /' ${WRSH})

if [ "${MAX_TX#[0-9]*}" != "$MAX_TX" ]; then
    ARGS="--max_tx $MAX_TX"
    shift
else
	 WRTD_ID=$1   
fi
ARGS="$ARGS $@"


/usr/local/bin/wrtd 2>&1  $WRTD_OPTS  $ARGS tx
