#!/bin/sh
# wrtd_txi message ... small integer :: send default

MAX_TX=${1:-1}
ARGS=""

if [ "${MAX_TX#[0-9]*}" != "$MAX_TX" ]; then
    ARGS="--max_tx $MAX_TX"
    shift
fi
ARGS="$ARGS $@"

source /dev/shm/wr.sh

if [ "x$1" = "x" ] || [ "$1" = "0" ] || [ $1 -le 1000 ]; then
	WRTD_ID=${WRTD_ID:-$(hostname)}
else
	WRTD_ID=$1
fi

/usr/local/bin/wrtd 2>&1 txi $WRTD_ID


