#!/bin/sh

MAX_TX=${1:-1}
ARGS=""

if [ "${MAX_TX#[0-9]*}" != "$MAX_TX" ]; then
    ARGS="--max_tx $MAX_TX"
    shift
fi
ARGS="$ARGS $@"

source /dev/shm/wr.sh

/usr/local/bin/wrtd 2>&1  --tickns $WRTD_TICKNS --dns $WRTD_DNS -v $WRTD_VERBOSE $ARGS tx $WRTD_ID 


