#!/bin/sh
TX_COUNT=${1:-1}

WRTD_DNS=50000000
WRTD_NICE=-10
WRTD_VERBOSE=0
WRTD_TICKNS=50000
WRTD_TX=1
WRTD_RX=1

[ -e /mnt/local/sysconfig/wr.sh ] && source /mnt/local/sysconfig/wr.sh

/bin/nice -n $WRTD_NICE /usr/local/bin/wrtd --tickns $WRTD_TICKNS --dns $WRTD_DNS -v $WRTD_VERBOSE --max_tx $TX_COUNT tx &


