#!/bin/sh
# wrtd_txi message ... small integer :: send default
export WRTD_DELTA_NS=50000000
export WRTD_NICE=-10
export WRTD_VERBOSE=0
export WRTD_TICKNS=50000

[ -e /mnt/local/sysconfig/wr.sh ] && source /mnt/local/sysconfig/wr.sh

if [ "x$1" = "x" ] || [ "$1" = "0" ] || [ $1 -le 1000 ]; then
	WRTD_ID=${WRTD_ID:-$(hostname)}
else
	WRTD_ID=$1
fi

/usr/local/bin/wrtd 2>&1 txi $WRTD_ID


