#!/bin/sh
NAME=$0
RESET=0
TX=0
PORT=4280
if [ "x$1" = "x1" ]; then
	[ "${NAME%%reset*}" != "$NAME" ] && RESET=1
	[ "${NAME%%rx*}" != "$NAME" ] TX=1
	
	[ $RESET -ne 0 ] && cp /mnt/local/sysconfig/wr.sh /etc/acq400/11/wr.sh
	[ $TX ne 0 ] && PORT=4281
	printf '\030' | nc localhost $PORT	
fi
