#!/bin/sh

SITE=${SITE:-${1:-1}}

train() {
STF=/var/run/acq480_train

source /dev/acq400.1.knobs/train_states

echo BUSY TRAIN starts >$STF
set.site $SITE train=$ACQ480_RESET
set.site $SITE acq480_setPatDeskew=0
set.site $SITE acq480_setPatSync=0
set.site $SITE train=$ACQ480_START
set.site $SITE acq480_setPatDeskew=1
set.site $SITE train=$ACQ480_DESKEW
DESKEW_DONE=$(get.site $SITE train)
if [ $DESKEW_DONE -ne $ACQ480_DESKEW_DONE ];then
	echo DESKEW failed
	echo FAIL DESKEW failed >$STF
	exit 1
fi
set.site $SITE acq480_setPatSync=1
set.site $SITE train=$ACQ480_SYNC
SYNC_DONE=$(get.site $SITE train)
if [ $SYNC_DONE -ne $ACQ480_SYNC_DONE ]; then
	echo SYNC failed
	echo FAIL SYNC failed >$STF
	exit 1
fi
set.site $SITE acq480_setPatSync=0
set.site $SITE train=$ACQ480_ACTIVATE
echo LINK activated
echo GOOD LINK activated >$STF
exit 0
}

if [ "x$2" = "xonce" ]; then
	train
else
	down=1
	let count=0
	while [ $down -ne 0 ]; do
		let count=$count+1
		if [ $count -gt 20 ]; then
			echo ERROR: failed to train in 20 attempts
			exit 1
		fi
		acq480_train $SITE once
		down=$?
	done
	exit 0
fi
