#!/bin/sh
# if there's a previous hanging instance, kill it and drop out
# client can retry at an appropriate moment to restart..

SITE=${1:-0}
PID=/var/run/acq400_stream.$SITE.pid

source /etc/sysconfig/acq400.conf

teardown() {
if [ -e $PID ]; then
	(
	echo before
	ps -o pid,pgid,comm | grep $(cat $PID)
	kill -9 -$(cat $PID)
	echo after
	ps -o pid,pgid,comm | grep $(cat $PID)
	rm $PID
	) 2>&1 >/tmp/acq400_streamd.log
fi
}

teardown
