#!/bin/sh
# if there's a previous hanging instance, kill it and drop out
# client can retry at an appropriate moment to restart..


init_stream() {
SITE=$1
PID=/var/run/acq400_stream.$SITE.pid


source /etc/sysconfig/acq400.conf >/dev/null

acq400_teardown $SITE
echo $$ > $PID

STREAM_OPTS=

if [ -e /etc/sysconfig/acq400_streamd.conf ]; then
	source /etc/sysconfig/acq400_streamd.conf
fi
if [ -e /etc/sysconfig/acq400_streamd.$SITE.conf ]; then
	source /etc/sysconfig/acq400_streamd.$SITE.conf 
fi
if [ -x /mnt/local/acq400_streamd.$SITE.init ]; then
	/mnt/local/acq400_streamd.$SITE.init
elif [ -x /etc/sysconfig/acq400_streamd.$SITE.init ]; then
	(/etc/sysconfig/acq400_streamd.$SITE.init) 
fi
SITE_KNOBS=/etc/acq400/$SITE
if [ -e $SITE_KNOBS ]; then
	if [ -e $SITE_KNOBS/SAMPLE_SIZE ]; then
		SAMPLE_SIZE="-w $(cat $SITE_KNOBS/SAMPLE_SIZE)"
	fi
	if [ -e $SITE_KNOBS/OVERSAMPLING ]; then
		OVERSAMPLING="-O $(cat $SITE_KNOBS/OVERSAMPLING)"
	fi
	SITE_ARGS=$(eval echo \$SITE${SITE}_ARGS)
fi

RUN0_READY=/etc/acq400/0/run0_ready

if [ $SITE -eq 0 ]; then
	sites=
	SSPEC=$(awk '{print $2}' </dev/acq400.0.knobs/aggregator)
	
	eval $SSPEC
	while [ "x$sites" = "x" -o "x$sites" = "xnone" ]; do
		sleep 1
		logger -t acq400_streamd site0 waiting for sites
		SSPEC=$(awk '{print $2}' </dev/acq400.0.knobs/aggregator)
		eval $SSPEC	
	done
	logger -t acq400_streamd site0 $SSPEC
	while [ ! -e $RUN0_READY ]; do
		sleep 0.2
		logger -t acq400_streamd site0 waiting for $RUN0_READY
	done
fi
}

SITE=$1
LOG=/var/log/acq400_streamd_$SITE.log

init_stream $SITE 2>&1 >$LOG
jobs >>$LOG
echo $SAMPLE_SIZE $OVERSAMPLING $SITE >>$LOG

if [ "x$SSPEC" != "x" ]; then
#	echo SSPEC $SSPEC
	SSPEC="--$SSPEC"
fi

if [ "x$ACQ400D_TRIG" = "xsoft_trigger" ]; then
	STREAM_OPTS="$STREAM_OPTS --soft-trigger=1"	
fi
echo acq400_stream $SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE  >>$LOG
acq400_stream $SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE 





