#!/bin/sh
# if there's a previous hanging instance, kill it and drop out
# client can retry at an appropriate moment to restart..

source /usr/local/bin/init_stream

SITE=$1
LOG=/var/log/acq400_streamd_$SITE.log

init_stream $SITE 2>&1 >$LOG
jobs >>$LOG
echo $SAMPLE_SIZE $OVERSAMPLING $SITE >>$LOG

STREAM_OPTS="$STREAM_OPTS --state-file /dev/shm/state"

if [ "x$ACQ400D_TRIG" = "xsoft_trigger" ]; then
	STREAM_OPTS="$STREAM_OPTS --soft-trigger=1"	
fi

if [ -e /mnt/local/acq400_stream ]; then
	ACQ400_STREAM=/mnt/local/acq400_stream
else
	ACQ400_STREAM=acq400_stream
fi

echo $ACQ400_STREAM --$SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE  >>$LOG
$ACQ400_STREAM --$SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE 2>/dev/null





