#!/usr/local/bin/expect

set PLAN "/usr/local/CARE/Si5317-plan"
set SITE 1

if { [info exists ::env(SITE) ] } {
	set SITE $::env(SITE)
}

if { [info exists ::env(PLAN) ] } {
	set PLAN $::env(PLAN)
}

set KPATH "/dev/acq480/$SITE/JC"
set KNOBS {FRQTBL FRQSEL3 FRQSEL2 FRQSEL1 FRQSEL0}

proc setFile {path value} {
#	puts "setFile $path=$value"
	set fp [open $path "w"]
	puts $fp $value
	close $fp
}
proc setKnob {knob bit} {
	global KPATH
	
	if { $bit == "M" } {
		setFile $KPATH/.direction.$knob in
	} else {
		setFile $KPATH/.direction.$knob out
		if { $bit == "H" } {
			setFile $KPATH/$knob 1
		} else {
			setFile $KPATH/$knob 0
		}
	}
}
proc setFreq {fc plan} {
	global KNOBS

	setKnob DBL2_BY 0

	lassign $plan pn fmin fmax FRQTBL FRQSEL
	set bits [split "$FRQTBL$FRQSEL" {}]
	puts "fc=$fc plan=$pn $bits"
	set ib 0
	foreach bit $bits {
		set knob [lindex $KNOBS $ib] 
		setKnob $knob $bit
		incr ib
	}
	setKnob RESETn L
	setKnob RESETn H
}


proc setBypass {} {
	puts "bypass"
	setKnob DBL2_BY 1
	setKnob RESETn L
	setKnob RESETn H
}

array set PLANS {}

proc getPlans {} {
	global PLAN PLANS
	set pf [open $PLAN "r"]
	set ln 0

	while { [gets $pf line] >= 0 } {
		lassign $line pn FRQTBL FRQSEL fmin fc fmax
		if { $pn > 10 } {
			set PLANS($fc) [list $pn $fmin $fmax $FRQTBL $FRQSEL]
		}
		incr ln
	}
#	puts "processed $ln plans"
}

# main processing starts here

if { $::argc > 0 } {
	set fx [lindex $::argv 0]

	if { $fx == 0 } {
		setBypass
		exit 0
	}
	set fplan1 0
	getPlans
	set keys [lsort -real [array names PLANS]] 

	foreach fplan $keys {
		if {$fx < $fplan} {
			if {$fplan == 0} {
				puts "ERROR $fx < fmin=$fplan"
				exit 1
			}
			puts "$fplan1 < $fx < $fplan"
			set err1 [expr $fx - $fplan1]
			set err2 [expr $fplan - $fx]
			if {$err1 < $err2} {
				setFreq $fplan1 $PLANS($fplan1)
			} else {
				setFreq $fplan1 $PLANS($fplan)
			}
			exit 0
		}
		set fplan1 $fplan
	}

	puts "ERROR $fx is too high"
	exit 1
} else {
	puts "USAGE: acq480-jc-setup FREQ"
	exit 1
}
