#!/bin/sh
# if there's a previous hanging instance, kill it and drop out
# client can retry at an appropriate moment to restart..

source /usr/local/bin/init_stream

SITE=$1
LOG=/var/log/acq400_streamd_$SITE.log

init_stream $SITE 2>&1 >$LOG
jobs >>$LOG
echo $SAMPLE_SIZE $OVERSAMPLING $SITE >>$LOG

if [ "x$ACQ400D_TRIG" = "xsoft_trigger" ]; then
	STREAM_OPTS="$STREAM_OPTS --soft-trigger=1"	
fi
echo acq400_stream --$SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE  >>$LOG
acq400_stream --$SSPEC $STREAM_OPTS $SAMPLE_SIZE $OVERSAMPLING $SITE 





