#!/bin/sh
# $1=pagename, $2=site
if [ "x$2" = "x" ]; then
	exit 1
fi

/usr/bin/logger -t acq420.init add_webpage $1 $2 01

while [ ! -e /var/www/d-tacq/acq_main_page.html ]; do
	sleep 1
done

TITLE=$(basename $1)
sed -ie '/TABAPPEND/ {
i       <li><a title="'$TITLE'" href="acq_info_page.html">'$TITLE'</a></li>
}' /var/www/d-tacq/acq_main_page.html
[ "$2" != "nomon" ] && /bin/nice /usr/local/bin/monitorregs $1 &
/usr/bin/logger -t acq420.init add_webpage $1 $2 99

