#!/bin/sh

SITE=${1:-0}
KNOBS=/dev/acq400.${SITE}.knobs
MODEL=$(cat $KNOBS/module_name)


echo "dac_range_ALL=dac_range_??" >/etc/acq400/${SITE}/groups	
echo +++ initializing DACs for $MODEL
echo "file acq400_drv.c +p"   >/sys/kernel/debug/dynamic_debug/control
echo "file acq400_sysfs.c +p" >/sys/kernel/debug/dynamic_debug/control
set.sys ${KNOBS}/dacreset 1
set.sys ${KNOBS}/dacreset 0
set.sys ${KNOBS}/dacspi 0x300000
set.sys ${KNOBS}/dacspi 0x400002
case $MODEL in
ao428elf)
	set.sys ${KNOBS}/dacspi 0x200002;;
*)
	set.sys ${KNOBS}/dacspi 0x200000;;
esac

echo "file acq400_drv.c -p"   >/sys/kernel/debug/dynamic_debug/control
echo "file acq400_sysfs.c -p" >/sys/kernel/debug/dynamic_debug/control

ln -s /usr/local/bin/wavegen /etc/acq400/$SITE

for gx in ${KNOBS}/G?; do
	[ -e $gx ] && set.sys $gx 32767
done


case $MODEL in
ao428elf)
	(cd /usr/local/lib/modules/
	/sbin/insmod adt7x10.ko
	/sbin/insmod adt7410.ko
	/sbin/insmod ao428.ko)
	mkdir /dev/hwmon/4
	ln -s /sys/class/hwmon/hwmon4/device/temp1_input /dev/hwmon/4/temp
	ln -s /sys/class/hwmon/hwmon4/device/temp1_input /etc/acq400/2/temp
	ln -s /usr/local/CARE/dac20_autozero /etc/acq400/2/dac20_autozero
	;;
esac

cat - >>/etc/acq400/$SITE/groups <<EOF
dac_range_XX=dac_range_[0-9]*
AO_ALL=AO_[0-9]*
EOF

