#!/bin/sh

SITE=${1:-0}
KNOBS=/dev/acq400.${SITE}.knobs

echo "dac_range_ALL=dac_range_??" >/etc/acq400/${SITE}/groups	
echo +++ initializing DACs 
#echo "file acq400_drv.c +p"   >/sys/kernel/debug/dynamic_debug/control
#echo "file acq400_sysfs.c +p" >/sys/kernel/debug/dynamic_debug/control
set.sys ${KNOBS}/dacreset 1
set.sys ${KNOBS}/dacreset 0
set.sys ${KNOBS}/dacspi 0x300000
set.sys ${KNOBS}/dacspi 0x400002
set.sys ${KNOBS}/dacspi 0x200000

#echo "file acq400_drv.c -p"   >/sys/kernel/debug/dynamic_debug/control
#echo "file acq400_sysfs.c -p" >/sys/kernel/debug/dynamic_debug/control

ln -s /usr/local/bin/wavegen /etc/acq400/$SITE
