#!/bin/sh

SITE=${1:-2} 
SPAN=${2:-0}
/sys/kernel/debug/acq400/acq400.2/spans/

for sp in /sys/kernel/debug/acq400/acq400.${SITE}/spans/??
do
	set.sys $sp $SPAN
done

set.sys /dev/acq400.${SITE}.knobs/dacreset_device 1

