#!/bin/sh

SITE=${1:-0}
KNOBS=/dev/acq400.${SITE}.knobs
echo +++ initializing DACs 

ln -s /usr/local/bin/wavegen /etc/acq400/$SITE

SPANS=/sys/kernel/debug/acq400/acq400.${SITE}/spans

for spchan in ${SPANS}/??
do
	ln -s $spchan /etc/acq400/${SITE}/range$(basename $spchan)
done

INITS=/sys/kernel/debug/acq400/acq400.${SITE}/init/


for ichan in ${INITS}/??
do
	ln -s $ichan /etc/acq400/${SITE}/init$(basename $ichan)
done

ln -s /etc/acq400/${SITE}/dacreset_device /etc/acq400/${SITE}/range99
ln -s ${MODP}/awg_seg /etc/acq400/${SITE}/awg_seg

cat - <<EOF >>/etc/acq400/$SITE/groups
range=range[0-9]*
init=init[0-9]*
AO_ALL=AO_[0-9]*
EOF
