#!/bin/sh
# bos : Big One Shot

if [ "x$1" = "xdefault" ]; then
	PRE=0
else
	PRE=${1:-0}
fi
POST=${2:-1000000}
VERBOSE=${3:-0}


if [ -e /etc/acq400/0/transient ]; then
	source /etc/acq400/0/transient
fi
if [ "$1" = "-" ]; then
	echo -n 'bos>'
	read PRE POST VERBOSE
	PRE=0
fi

NC=$(get.site 0 NCHAN)
if [ "x$(get.site 0 data32)" = "1" ]; then
	WS=4
else
	WS=2
fi
SITES=$(get.site 0 aggregator | awk '{ print $2 }')
if [ $VERBOSE -gt 0 ]; then
	echo "acq400_stream --verbose $VERBOSE --null-copy --no_demux \
	--nchan=$NC -w=$WS --pre=$PRE --post=$POST --$SITES 0"
fi

exec acq400_stream --verbose=$VERBOSE --null-copy --no_demux \
	--nchan=$NC -w=$WS --pre=$PRE --post=$POST --$SITES 0

