#!/bin/bash
# sourced from run0 and play0

# input $sites
# output SS

nspad=${nspad:-0}

let nchan=0
d32=""
ositelist=$sitelist
sitelist=""
sep=""

SS=$nspad*4

for site in $sites
do
	s_root=/etc/acq400/$site
	wpc=1

	if [ -e ${s_root}/data32 ]; then
		echo $nchan > ${s_root}/AGIX
		site_d32=$(cat ${s_root}/data32)
		active_chan=$(cat ${s_root}/active_chan)
		echo site_d32 $site_d32		
		if [ $site_d32 -eq 1 ]; then
			sss=4
		else
			sss=2
		fi
		echo Hello sss $sss d32 $d32 site_d32 $site_d32
		if [ "x$d32" = "x" ]; then
			d32=$site_d32
		elif [ $d32 -ne $site_d32 ]; then
			echo "WARNING: mixed data size"
		fi
		nchan=$((${nchan}+${active_chan}))
		SS=$(($SS+$active_chan*$sss))
		sitelist="${sitelist}${sep}${site}"
		sep=","
	else
		echo "ERROR: site $site does not exist"
	fi
done

if [ -z $d32 ]; then
	nchan=0
elif [ $d32 -eq 1 ]; then
	nchan=$(($nchan+$nspad))
else
	nchan=$(($nchan+$nspad*2))
fi


