#!/bin/bash
# sourced from run0 and play0

# input $sites
# output SS sample size, nchan, d32 (master size)

let nchan=0
d32=""
sitelist=""
sep=""

nspad=${nspad:-0}
d32c=$nspad
d16c=0

for site in $sites
do
	s_root=/etc/acq400/$site
	if [ -e ${s_root}/data32 ]; then
		echo $nchan > ${s_root}/AGIX
		site_d32=$(cat ${s_root}/data32)
		active_chan=$(cat ${s_root}/active_chan)
		if [ $site_d32 -eq 1 ]; then
			d32c=$(($d32c+$active_chan))
		else
			d16c=$(($d16x+$active_chan))
		fi
		if [ "x$d32" = "x" ]; then
			d32=$site_d32
		elif [ $d32 -ne $site_d32 ]; then
			echo "WARNING: mixed data size"
		fi
		sitelist="${sitelist}${sep}${site}"
		sep=","
	else
		echo "ERROR: site $site does not exist"
	fi
done


if [ -z $d32 ]; then
    SS=0
	nchan=0
elif [ $d32 -eq 1 ]; then
	nchan=$(($d32c+$d16c/2))
	SS=$(($nchan*4))
else
	nchan=$(($d16c+$d32c*2))
	SS=$(($nchan*2))
fi

echo "get_site_total_size d32:$d32 nchan:$nchan d32c:$d32c d16c:$d16c SSB:$SS"


