#!/bin/sh

SF=acq400_streamd.0.conf-soft_trigger
SRC=/usr/local/CARE/$SF
DST=/etc/sysconfig/acq400_streamd.0.conf


if [ "$1" = "remove" ]; then
	echo remove auto-soft_trigger
	sed -ie "/$SF/d" /mnt/local/rc.user
	rm $DST
else
	if [ -e /mnt/local/rc.user ]
		grep -q $SF /mnt/local/rc.user
		if [ $? -eq 0 ]; then
			echo exists already ..
			exit 0
		fi
	fi
	echo "cp $SRC $DST" >>/mnt/local/rc.user
	cp $SRC $DST
fi
