#!/bin/sh


OLDPID=$(ps | grep '[0-9] inetd /etc/inetd.ch.con' | awk '{ print $1 }')
if [ "$OLDPID" != "" ]; then
	kill $OLDPID
fi 

NCHAN=$(cat /etc/acq400/0/NCHAN)
let P0=53000

# 4226 stream tcp nowait root acq400_knobs acq400_knobs 6
cat - > /etc/inetd.ch.conf <<EOF
# $NCHAN $(date)
53000 stream tcp nowait root run.transient.service run.transient.service gash
EOF


let cix=1

eval $(cat /etc/acq400/0/aggregator)
IFS=,
for site in $sites
do
#	echo site $site  /dev/acq400/data/$site/
	for ch in /dev/acq400/data/$site/??
	do
        	let px=$P0+$cix        
        	echo >>/etc/inetd.ch.conf \
        		"$px stream tcp nowait root cat cat $ch"
		chl=$(printf "%02d" $cix)
		echo "acq400_ch$chl $px/tcp	# ch $ch transient data" >>/etc/services
        	let cix=$cix+1
        done
done

if [ -d /etc/acq400/2 ] && [ $(get.site 2 module_name) = "qen" ]; then
	echo >>/etc/inetd.ch.conf \
	"53999 stream tcp nowait root bpaste bpaste /dev/acq400/data/2/01 /dev/acq400/data/2/02"
	echo "acq400_qen	52999/tcp # qen data" >>/etc/services
fi

inetd /etc/inetd.ch.conf
