#!/bin/sh

CMD=${1:-status}
MGB1=${2:-0}
MGB2=${3:-0}

PIDF=/var/run/mgt_load.pid

is_running() {
	for pid in $(ps | awk '{ print $1 }')
	do
		if [ $pid = $1 ]; then
			echo 1; break
		fi
	done
	echo 0
}

load_block() {
	logger -t mgt_load load_block $MGB1 $MGB2
	echo $MGB1 $MGB2 > /dev/mgt400.A.push_desc &
	echo $! > $PIDF
	wait
	logger -t mgt_load cleanup
	rm $PIDF
}
load() {
	if [ -e $PIDF ] && [ is_running $(cat $PIDF) ]; then
		echo "ERROR: previous process still running, quitting"
	else
		set.mgt_direction_inbound 0
		load_block &
	fi		
}

query() {
	if [ -e $PIDF ] && [ is_running $(cat $PIDF) ]; then
		echo BUSY $(cat $PIDF)
	else
		echo IDLE
	fi
}


case $CMD in
load)	load;;
*)	query;;
esac
