#!/bin/sh

set.site 1 SIG:SAMPLE_COUNT:RESET 1

DCRST=/dev/gpio/MGTDRAM/DCRST
if [ -e $DCRST ]; then
	set.sys $DCRST 1
	echo DRAM CONTROLLER RESET
	set.sys $DCRST 0
fi
mgt_load load 0 ${1:-99}
streamtonowhered start

while [ 1 ]; do
	STATUS=$(mgt_load)
	echo $STATUS $(get.site 1 SIG:SAMPLE_COUNT:COUNT)
	if [ "$STATUS" = "IDLE" ]; then
		break
	else
		sleep 1
	fi
done

streamtonowhered stop


