#!/bin/sh

set.site 1 SIG:SAMPLE_COUNT:RESET 1


eval $(get.site 0 aggregator)
BL=$(cat /sys/module/acq420fmc/parameters/bufferlen)
set.sys /dev/acq400.0.knobs/AXI_DMA_len $BL
set.sys /dev/acq400.0.knobs/bufferlen $BL
NO_OPTIMISE_BUFFERLEN=y run0 $sites

DCRST=/dev/gpio/MGTDRAM/DCRST
if [ -e $DCRST ]; then
	set.sys $DCRST 1
	echo DRAM CONTROLLER RESET
	set.sys $DCRST 0
fi

nb=${1:-99}
nb=$(($nb+2))
[ $nb -gt 2000 ] && $nb=2000

mgt_load load 0 $nb
streamtonowhered start

while [ 1 ]; do
	STATUS=$(mgt_load)
	echo $STATUS $(get.site 1 SIG:SAMPLE_COUNT:COUNT)
	if [ "$STATUS" = "IDLE" ]; then
		break
	else
		sleep 1
	fi
done

streamtonowhered stop


