#!/bin/sh

mgt_load load 0 ${1:-99}
streamtonowhered start

while [ 1 ]; do
	STATUS=$(mgt_load)
	echo $STATUS
	if [ "$STATUS" = "IDLE" ]; then
		break
	else
		sleep 1
	fi
done

streamtonowhered stop


