#!/usr/local/bin/expect
# runs any command in cwd
# runs ONLY commands in cwd

proc prompt {} {
	puts -nonewline stdout 'mgtsh> '
}

cd /dev/shm/mgtsh
prompt
while {[gets stdin cmd]} {
	./$cmd
	prompt
}
