#!/bin/sh

[ -e /etc/mgtsh.env ] && source /etc/mgtsh.env

if [ -e /dev/shm/mgtd.job ]; then
	source /dev/shm/mgtd.job
	case $CMD in
	mgt_offload|mgt_run_shot)
		time taskset 0x2 $CMD $ARGS;;
	*)
		echo "ERROR in /dev/shm/mgt.job CMD not recognized";;
	esac
else
	echo "IDLE: no job"
fi
echo END

