#!/bin/sh

DEV=${1:-acq480.1}
DIR=/proc/driver/acq480/${DEV}

#httpd doesn't like names with periods..
XMLNAME=${DEV%.*}${DEV#*.}

cCrR() {
cat - <<EOF
        <pageFormat>
                <noCols>$1</noCols>
                <colItems>$2</colItems>
        </pageFormat> 
EOF
}

C2R20=/dev/shm/c2rR20

[ -e $C2R20 ] || cCrR 2 20 > $C2R20

dump_regs() {
	cat $DIR/spibuf
}

ADDED_WEB=0

add_web() {
if [ -e /var/www/d-tacq/acq_main_page.html ]; then
	grep -q $DEV /var/www/d-tacq/acq_main_page.html
	if [ $? -ne 0 ]; then
		sed -ie '/TABAPPEND/ {
i       <li><a title="'$DEV'" href="acq_info_page.html">'$DEV'</a></li>
}' /var/www/d-tacq/acq_main_page.html
	fi
	ADDED_WEB=1
fi
}

monitor() {
	while [ 1 ]
	do
		[ $ADDED_WEB -eq 0 ] && add_web				
		dump_regs | fs2xml -k '' -o /dev/shm/$XMLNAME.xml -s $C2R20
		sleep 1		
	done
}

if [ "$(basename $0)" = "monitor_acq480_spi" ]; then
	if [ -d $DIR ]; then
		monitor
	else
		echo ERROR: monitor dir not found: $DIR
	fi
fi



