#!/bin/sh


[ "x$2" = "xnone" ] && exit 0

DEV=${1:-acq420.0}

if [ "$(basename $DEV)" != "$DEV" ] ; then
	DIR=$DEV
	DEV=$(basename $DEV)
	echo DIR $DIR DEV $DEV
	XMLNAME=$DEV
else
	DIR=/sys/kernel/debug/${DEV%.*}/${DEV}
#httpd doesn't like names with periods..
	XMLNAME=${DEV%.*}${DEV#*.}
fi


cCrR() {
cat - <<EOF
        <pageFormat>
                <noCols>$1</noCols>
                <colItems>$2</colItems>
        </pageFormat> 
EOF
}

C2R20=/dev/shm/c2rR20

[ -e $C2R20 ] || cCrR 2 20 > $C2R20


monitor() {
	echo monitor $XMLNAME.xml
	while [ 1 ]
	do
		dump_regs $DIR | fs2xml -k '' -o /dev/shm/$XMLNAME-new.xml -s $C2R20
		mv /dev/shm/$XMLNAME-new.xml  /dev/shm/$XMLNAME.xml 
		sleep 1		
	done
}

if [ "$(basename $0)" = "monitorregs" ]; then
	if [ -d $DIR ]; then
		monitor
	else
		echo ERROR: monitor dir not found: $DIR
	fi
fi



