#!/bin/sh
# configures site 0 aggregator.
# usage: run0 site1[,site2,..]

spad2nchan() {
	mode=$1
	nwords=$2
	case $mode in
	0)
		echo 0;;
	1)
		echo $nwords;;
	2)
		echo 1;;
	esac
}

if [ "x$1" = "x" ]; then
	source /etc/sites
	sitelist=$sites
	echo using default sitelist $sitelist
else
	sitelist=$1
fi
sites="$(echo $sitelist | tr , \ )"

echo sitelist: $sitelist
echo sites: $sites

rm -f /etc/acq400/0/run0_ready
acq400_teardown

let nchan=0
d32=""
ositelist=$sitelist
sitelist=""
sep=""

for site in $sites
do
	s_root=/etc/acq400/$site
	wpc=1

	if [ -e ${s_root}/data32 ]; then
		site_d32=$(cat ${s_root}/data32)
		active_chan=$(cat ${s_root}/active_chan)
		if [ "x$d32" = "x" ]; then
			d32=$site_d32
		else
			if [ $d32 -ne $site_d32 ]; then
				echo WARNING: mixed data size
				if [ $site_d32 -ne 0 ]; then 
					wpc=2
				fi
			fi
		fi
		let nchan="${nchan}+${active_chan}*${wpc}"
		sitelist="${sitelist}${sep}${site}"
		sep=","
	else
		echo "ERROR: site $site does not exist"
	fi
done

# channels per word
if [ $d32 -eq 1 ]; then
	cpw=1
else
	cpw=2
fi

spad3="$(tr , \  </etc/acq400/0/spad)"
let nspad=$(spad2nchan $spad3)

let nchan="$nchan+$nspad*$cpw"

if [ ! -e /etc/acq400/0/NCHAN ] || [ $nchan -ne $(cat /etc/acq400/0/NCHAN) ]
then
	echo setting NCHAN=$nchan data32=$d32
	set.sys /etc/acq400/0/NCHAN $nchan
	set.sys /etc/acq400/0/data32 $d32
	/usr/local/bin/ai_monitor_all start	
fi
set.sys /etc/acq400/0/sites ${sitelist}

# worktodo LCM wanted .. and, what if the bufferlen is something other than 1MB

let BLEN=$(cat /sys/module/acq420fmc/parameters/bufferlen)

if [ $BLEN -eq 1048576 ]; then
	case $nchan in
	48|80|96|160)
		BLEN=1044480;;
	*)
		BLEN=1048576;;
	esac
	set.sys /dev/acq400.0.knobs/bufferlen $BLEN
fi

	
set.sys /dev/acq400.0.knobs/aggregator 0
set.sys /dev/acq400.0.knobs/data_engine_0 0
set.sys /dev/acq400.0.knobs/data_engine_0 aggregator=1 
set.sys /dev/acq400.0.knobs/aggregator threshold=16384 sites=${sitelist}
echo 1 > /etc/acq400/0/run0_ready




