#!/bin/sh
# configures site 0 aggregator.
# usage: run0 site1[,site2,..]

spad2nchan() {
	mode=$1
	nwords=$2
	case $mode in
	0)
		echo 0;;
	1)
		echo $nwords;;
	2)
		echo 1;;
	esac
}

if [ "x$1" = "x" ]; then
	source /etc/sites
	sitelist=$sites
	echo using default sitelist $sitelist
else
	sitelist=$1
fi
sites="$(echo $sitelist | tr , \ )"

echo sitelist: $sitelist
echo sites: $sites

rm -f /etc/acq400/0/run0_ready
acq400_teardown

spad3="$(tr , \  </etc/acq400/0/spad)"
let nspad=$(spad2nchan $spad3)


source get_site_total_size

if [ ! -e /etc/acq400/0/NCHAN ] || [ $nchan -ne $(cat /etc/acq400/0/NCHAN) ]
then
	echo setting NCHAN=$nchan data32=$d32
	set.sys /etc/acq400/0/NCHAN $nchan
	set.sys /etc/acq400/0/data32 $d32
	/usr/local/bin/ai_monitor_all start	
fi
set.sys /etc/acq400/0/sites ${sitelist}


echo $SS > /etc/acq400/0/ssb

set.sys /dev/acq400.0.knobs/optimise_bufferlen $SS 

	
set.sys /dev/acq400.0.knobs/aggregator 0
set.sys /dev/acq400.0.knobs/data_engine_0 0
set.sys /dev/acq400.0.knobs/data_engine_0 aggregator=1 
set.sys /dev/acq400.0.knobs/aggregator threshold=16384 sites=${sitelist}
echo 1 > /etc/acq400/0/run0_ready




