#!/bin/sh

if [ "x$1" = "xbg" ]; then
	daemon si5326_tune_phase
	exit 0
fi

adjust() {
	set.site 0 si5326_step_phase $1 >/dev/null;get.site 0 wr_clk_pv3
}

show_state() {
	good=0; busy=0
    [ "$STATE" = "ST_FINISHED" ] && good=1
    [ "$STATE" = "ST_FINISHED" ] || [ "$STATE" = "ST_OFF" ] || busy=1
	printf '%2d %20s %2d :%s %d %d\n' $1 $2 $3 $4 $busy $good | tee /dev/shm/si5326_tune_phase.state
}

(
STATE=ST_COARSE_TO_X01
iter=0
show_state $iter $STATE 0 0

while [ "$STATE" != "ST_FINISHED" ]; do
	iter=$(($iter+1))
	NSTATE=$STATE

	case $STATE in
	ST_COARSE_TO_X01)
		PVC=$(adjust -3)
		case $PVC in
		1|5)
			NSTATE=ST_FINE_TO_01X;;
		esac;;
	ST_FINE_TO_01X)
		PVC=$(adjust -1)
		case $PVC in
		2|3)
			NSTATE=ST_FINE_TO_1XX;;
		esac;;
	ST_FINE_TO_1XX)
		PVC=$(adjust -1)
		case $PVC in
		4|5|6|7)
			NSTATE=ST_COARSE_FINAL;;
		esac;;
	ST_COARSE_FINAL)
		PVC=$(adjust -3)
		NSTATE=ST_FINISHED;;
	esac
	jump='--'
	[ "$STATE" != "$NSTATE" ] && jump='=>'
	show_state $iter $STATE $PVC $jump
	STATE=$NSTATE
done

show_state $iter $STATE $PVC $jump

) 2>&1 | tee /dev/shm/si5326_tune_phase.log


