#!/bin/sh

while [ ! -e /etc/acq400/0/slowmon_hw ]; do
	sleep 1
done

SLOWMON_HW=$(cat /etc/acq400/0/slowmon_hw)
#echo SLOWMON_HW $SLOWMON_HW
[ $SLOWMON_HW -eq 1 ] && exec slowmon_hw

FIN=$(cat /etc/acq400/0/slowmon_fin)
FS=$(cat /etc/acq400/0/slowmon_fs)
SPB=$(echo $FIN $FS | awk '{ nb=int($2/$1); print(nb>0? nb: 1) }')
SPP=$(cat /etc/acq400/0/slowmon_nacc)
SPAD=$(cat /etc/acq400/0/spad)
#echo exec bbq_send_ai --stdout=1 --samples_per_packet=$SPP --packets_per_buffer=$SPB --spad=$SPAD
[ $SLOWMON_HW -ne 1 ] && exec bbq_send_ai --stdout=1 --samples_per_packet=$SPP --packets_per_buffer=$SPB --spad=$SPAD 2>/dev/null


