#!/bin/sh
# streams to nowhere .. get streaming!

SERVICE=nowhere
PIDF=/var/run/run.$SERVICE.pid
#LOG=/var/log/run.$SERVICE.log
LPORT=$(get-port-from-service acq4xx-$SERVICE-console)

start() {
	/usr/local/bin/procServ --restrict -c / -p $PIDF $LPORT \
		/usr/local/bin/streamtonowhere
}

stop() {
        if [ -r ${PIDF} ]; then
        	echo 1 > /dev/acq400.0.knobs/estop
                kill -s TERM $(cat ${PIDF})
                rm ${PIDF}
        fi
}

status() {
	if [ -r ${PIDF} ]; then
		echo running $(cat ${PIDF})
	else
		echo stopped
	fi
}

case $1 in
start|"")
        start;;
stop)
        stop;;
status)
	status;;
*)
        echo "USAGE streamtonowhered  start\|stop";;
esac


