#!/bin/sh

if [ -e /etc/profile.d/bos.sh ]; then
	source /etc/profile.d/bos.sh
fi

PREMAX=${PREMAX:-0}
POSTMAX=${POSTMAX:-4000000}
DEMUX=${DEMUX:-1}

if [ -e /dev/shm/transient_settings ]; then
	source /dev/shm/transient_settings
fi

SOFT_TRIGGER=${SOFT_TRIGGER:-1}

if [ "$(basename $0)" = "transient" ]; then

	if [ "x$1" = "x" ]; then
		cat /dev/shm/transient_settings
		exit 0
	fi

	validate() {
		let xx=$1
		let x1=$2
		let x2=$3
		if [ $xx -lt $x1 ]; then
			echo $x1
		elif [ $xx -gt $x2 ]; then
			echo $x2
		else
			echo $xx
		fi
	}
	NEWS=""

	for pair in $*
	do
		key=${pair%=*}
		val=${pair#*=}
		case $key in
		PRE)	PRE=$(validate $val 0 $PREMAX);;
		POST)	POST=$(validate $val 0 $POSTMAX);;
		VERBOSE) VERBOSE=$(validate $val 0 3);;
		OSAM)	OSAM=$(validate $val 0 256);;
		DEMUX)	DEMUX=$(validate $val 0 1);;
		SOFT_TRIGGER)
			SOFT_TRIGGER=$(validate $val 0 1);;
		*)
			echo "ERROR: $pair not supported"
			exit 1;;
		esac
	done
	NEWS="PRE=$PRE POST=$POST OSAM=$OSAM DEMUX=$DEMUX SOFT_TRIGGER=$SOFT_TRIGGER"

	echo $NEWS > /dev/shm/transient_settings
fi	


