#!/usr/local/bin/expect

log_user 0
set timeout 1

if { $argc > 0 } {
	set wstate [lindex $argv 0]
} else {
	set wstate 0
}


spawn acq4xx-transient-console

set to_count 0

# STX STATE PRE POST ...
# 0   1     2 ...

set LINDEX_STATE 1

while { 1 } {
	expect {
		-re "\nSTX (\[0-9\]) (.*)\r" {
#			puts "match $expect_out(1,string)"
			set trailer [string trim $expect_out(2,string)]
#			puts trailer

			if { $wstate == 0 && "$trailer" eq "0 0 0 0" } {
				continue;
			}
			if { $expect_out(1,string) == $wstate } {
				exit 0
			}			
		}
		timeout {
			if {[ expr $to_count & 0x3 ] == 2 } {
				puts "timeout $to_count"
			}
			set cur_state [lindex [split [exec cat /dev/shm/state]] $LINDEX_STATE ]
			if { $cur_state == $wstate } {
				exit 0
			}
			incr to_count
		}
	}
}

