#!/usr/local/bin/expect

log_user 0
set timeout 1

if { $argc < 2 } {
	puts "wait_until PV VALUE"
	exit 1
}
set HN [exec hostname]
set PV $HN:[lindex $argv 0]
set VALUE [lindex $argv 1]

#puts "$PV $VALUE"

spawn camonitor $PV

set state INIT

while { $state != "FINI" } {
	expect {
		-re "$PV (\[0-9-\]+) (\[0-9:\.\]+) (\[^ \]+) .*\r" {
			set v1 $expect_out(3,string)
		}
		timeout {
			set vx [exec caget $PV]
			set v1 [lindex [split $vx " "] 1]	
		}
	}
	if { $state == "INIT" } {
		set v0 $v1
		set state WAIT4
	} else {
		if { $v1 != $v0 } {
			if { $v1 == $VALUE } {
				set finished 1
				set state FINI
			}
			puts "$v0 => $v1 $state"
			set v0 $v1
		}
	}
}

#puts "FINISHED $v0 -> $v1"




