#!/bin/sh

echo WORKTODO build_dsp_nodes.. ATD at site 14?. page 15
do_build_nodes()
{
        finit=0
        while [ $finit -eq 0 ]; do
                read M_DEV
                if [ "$M_DEV" = "" ]; then
                        finit=1;
                else
                        MAJOR=${M_DEV% *}
                        NAME=${M_DEV#* }
                        ID=${M_DEV%dsp*}

			mknod /dev/$NAME.event c $MAJOR 64
                fi
        done
}

do_build_nodes
