#!/bin/sh

SITE=${1:-0}
HISTO=/dev/acq420.${SITE}.histo

echo Histogram for $HISTO
hexdump -e '"%_ad : " 1/4 "%8d\n"' $HISTO | \
	awk '{if ($0 == "*") print $1; else printf("%10d : %d\n", $1*4, $3);}'\
	| grep -v ': 0'



